apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.27.2
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 5m0s
  releaseName: istio-base
  targetNamespace: istio-system
  values:
    global:
      istioNamespace: istio-system
    defaultRevision: default