apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m0s
  releaseName: istio-ingressgateway
  targetNamespace: istio-system
  values:
    gateways:
     istio-ingressgateway:
       name: istio-ingressgateway
       namespace: istio-system
       labels:
         app: istio-ingressgateway
         istio: ingressgateway
       service:
         type: LoadBalancer
         ports:
         - port: 80
           targetPort: 8080
           protocol: TCP
           name: http
         - port: 443
           targetPort: 8443
           protocol: TCP
           name: https