apiVersion: v1
kind: Namespace
metadata:
  name: whoami
  labels:
    istio-injection: enabled 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:v1.10.3
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
          
---

apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: whoami-registry
  namespace: whoami
spec:
  hosts:
  - registry.${internal_domain}
  gateways:
  - istio-system/${default_gateway}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: whoami.whoami.svc.cluster.local
        port:
          number: 80