apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gdllc-dev-tls
  namespace: istio-system
spec:
  secretName: gdllc-dev-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - gdllc.dev
