apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.27.0"
      sourceRef:
        kind: HelmRepository
        name: anti-sanctions
        namespace: flux-system
      interval: 1m
  releaseName: vault
  targetNamespace: vault
  values:
    global:
      enabled: true
      namespace: vault 
    injector:
      enabled: true
      metrics:  
        enabled: true
      resources:
        requests:
          memory: '256Mi'
          cpu: '250m'
        limits:
          memory: '256Mi'
          cpu: '250m'
    server:
      resources:
        requests:
          memory: '2Gi'
        limits:
          memory: '8Gi'
      dataStorage:
        size: '5Gi'
        storageClass: 'csi-s3'
      dev: 
        enabled: false
      standalone:
        enabled: false
      ha: 
        enabled: true
        replicas: 2
      ui:
        enabled: true

      


