apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault-httproute
  namespace: vault
spec:
  parentRefs:
  - name: main-gateway
    namespace: istio-system
  hostnames:
  - "vault.${cluster_domain}"
  rules:
  - backendRefs:
    - name: vault
      port: 8200