apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.19.1
  install:
    crds: Skip
  upgrade:
    crds: Skip
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: false