apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-s3
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-mountpoint-s3-csi-driver
      sourceRef:
        kind: HelmRepository
        name: anti-sanctions
        namespace: flux-system
      interval: 1m
  releaseName: csi-s3
  targetNamespace: kube-system
  values:
    s3:
      endpointUrl: https://s3.twcstorage.ru
      region: ru-1
    s3CredentialSecret:
      name: csi-s3-secret