apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-s3
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-s3
      sourceRef:
        kind: HelmRepository
        name: yandex-s3
        namespace: flux-system
      interval: 1m
  releaseName: csi-s3
  targetNamespace: kube-system
  values:
    secret:
      create: false
      name: csi-s3-secret 
    storageClass:
      create: true
      name: csi-s3
      singleBucket: "c2df1994-hq-default-csi"
      mounter: s3fs