apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-s3
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/scality/mountpoint-s3-csi-driver/helm-charts/scality-mountpoint-s3-csi-driver
  ref: 
    tag: v2.0.0
